name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install docker.io -y

      - name: Build Docker Image
        run: |
          docker build -t web-app:latest .

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: YOUR_EC2_PUBLIC_IP
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker stop web-app || true
            docker rm web-app || true
            docker run -d -p 80:80 --name web-app web-app:latest
